version: '3'

services:
  # Servicio MySQL
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: almohada
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: fimosis

  # Servicio WordPress
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "33:80"
    volumes:
      - ./wordpress:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: fimosis
      WORDPRESS_DB_NAME: wordpress

volumes:
  db_data:
